apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-service
  name: postgres-service
spec:
  externalName: sensor-project-334918:us-central1:sensor-project-db
  selector:
    app: postgres-service
  type: ExternalName
status:
  loadBalancer: {}